fragment GlobalsParts on Globals {
  __typename
  navigation {
    __typename
    logo
    navigationLinks {
      __typename
      text
      url
    }
  }
  footer {
    __typename
    logo
    mailingAddress
    shippingAddress
    phone
    email
  }
}

fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksHero {
      image
      heading
    }
    ... on PageBlocksValues {
      backgroundImage
      title
      quality1 {
        __typename
        title
        description
      }
      quality2 {
        __typename
        title
        description
      }
      quality3 {
        __typename
        title
        description
      }
    }
    ... on PageBlocksLocation {
      content
    }
    ... on PageBlocksMachineCarousel {
      sectionTitle
      buttonLabel
      machineCard {
        __typename
        image
        name
        description
        type
      }
    }
  }
}
